env:
  es6: true
  node: true
  browser: true
  es2021: true
  commonjs: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - google
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018 
  sourceType: module
settings:
  react:
    version: detect
plugins:
  - 'react-hooks'
  - react
  - '@typescript-eslint'
rules: {
  "react/prop-types": "off"
}
